/**
 * Word pools for Scramble, grouped by length. Each word carries a short
 * category hint (shown early, hidden at the hardest levels). All uppercase;
 * no spaces, no duplicate-heavy oddities that would make anagrams ambiguous.
 *
 * Pool size is a *freshness* budget, not decoration. A daily takes exactly 3
 * words from each length bucket (rounds are planned 3 × len 4, 3 × len 5 … 3 ×
 * len 8), so a given word surfaces every `size / 3` days. At 14 per bucket that
 * was once every five days — players recognised IRIS, LEMON and STORM coming
 * back in the opening rounds and the daily felt scripted. At 60 that became
 * twenty days, and buckets now run 77–83, i.e. a bit under a month.
 *
 * Keep every bucket at 75+, and keep words in the bucket that matches their
 * length — the difficulty ramp is built out of length alone.
 *
 * Two rules that keep a round *fair*, because the game accepts only an exact
 * match against the target word:
 *
 * 1. No two words in the same bucket may be anagrams of each other. The player
 *    would spell the other one, see a valid word, and be marked wrong.
 * 2. Avoid words that anagram to a common word fitting the same hint. LEMON's
 *    hint is "a sour yellow fruit" rather than "a fruit" for exactly this
 *    reason — MELON is not in the pool, but "a fruit" pointed at both.
 *
 * Both are checked by eye; rule 1 is mechanical enough to re-verify with a
 * sort-the-letters pass if this file grows again.
 */

export interface ScrambleWord {
  w: string;
  h: string;
}

export const WORD_POOLS: Record<number, ScrambleWord[]> = {
  4: [
    { w: "WOLF", h: "animal" },
    { w: "MOON", h: "in the sky" },
    { w: "FROG", h: "animal" },
    { w: "SALT", h: "in the kitchen" },
    { w: "KING", h: "royalty" },
    { w: "BOMB", h: "it explodes" },
    { w: "NEON", h: "a glowing gas" },
    { w: "RUBY", h: "a gem" },
    { w: "SNOW", h: "weather" },
    { w: "HERO", h: "the good guy" },
    { w: "MAZE", h: "you get lost in it" },
    { w: "LAVA", h: "from a volcano" },
    { w: "DUEL", h: "a one-on-one fight" },
    { w: "IRIS", h: "part of the eye" },
    { w: "BEAR", h: "animal" },
    { w: "HAWK", h: "a bird" },
    { w: "CROW", h: "a black bird" },
    { w: "MOTH", h: "an insect" },
    { w: "CRAB", h: "a sea animal" },
    { w: "SWAN", h: "a graceful bird" },
    { w: "GOAT", h: "animal" },
    { w: "MULE", h: "animal" },
    { w: "LYNX", h: "a wild cat" },
    { w: "TOAD", h: "animal" },
    { w: "FAWN", h: "a baby deer" },
    { w: "CLAW", h: "on a bear's paw" },
    { w: "FANG", h: "a sharp tooth" },
    { w: "NEST", h: "a bird's home" },
    { w: "HIVE", h: "bees live here" },
    { w: "VINE", h: "a climbing plant" },
    { w: "FERN", h: "a leafy plant" },
    { w: "BARK", h: "the skin of a tree" },
    { w: "TWIG", h: "a small branch" },
    { w: "HERB", h: "it flavours food" },
    { w: "DUNE", h: "a hill of sand" },
    { w: "REEF", h: "coral in the sea" },
    { w: "TIDE", h: "the sea rises and falls" },
    { w: "HAIL", h: "weather" },
    { w: "MIST", h: "weather" },
    { w: "GALE", h: "a strong wind" },
    { w: "DAWN", h: "the day begins" },
    { w: "DUSK", h: "the day ends" },
    { w: "STAR", h: "in the sky" },
    { w: "MARS", h: "a planet" },
    { w: "JADE", h: "a green gem" },
    { w: "OPAL", h: "a gem" },
    { w: "GOLD", h: "a precious metal" },
    { w: "IRON", h: "a metal" },
    { w: "ZINC", h: "a metal" },
    { w: "COAL", h: "you burn it" },
    { w: "OVEN", h: "in the kitchen" },
    { w: "FORK", h: "in the kitchen" },
    { w: "SOUP", h: "food" },
    { w: "TACO", h: "food" },
    { w: "PLUM", h: "a fruit" },
    { w: "LIME", h: "a green fruit" },
    { w: "MILK", h: "a drink" },
    { w: "HARP", h: "instrument" },
    { w: "DRUM", h: "instrument" },
    { w: "MASK", h: "it hides your face" },
    { w: "DEER", h: "animal" },
    { w: "LAMP", h: "in the house" },
    { w: "SOFA", h: "furniture" },
    { w: "ROOF", h: "part of a house" },
    { w: "ROPE", h: "tool" },
    { w: "NAIL", h: "hardware" },
    { w: "BOLT", h: "hardware" },
    { w: "GEAR", h: "machinery" },
    { w: "JUNE", h: "a month" },
    { w: "JULY", h: "a month" },
    { w: "MINT", h: "a green herb" },
    { w: "PEAR", h: "a fruit" },
    { w: "KALE", h: "a leafy green" },
    { w: "TUNA", h: "a fish" },
    { w: "CORN", h: "a grain" },
    { w: "TUBA", h: "a brass instrument" },
    { w: "BOOT", h: "footwear" },
    { w: "CAVE", h: "underground" },
    { w: "HAZE", h: "weather" },
    { w: "QUIZ", h: "a short test" },
    { w: "POEM", h: "writing" },
    { w: "KELP", h: "seaweed" },
    { w: "MOSS", h: "a plant" },
  ],
  5: [
    { w: "TIGER", h: "animal" },
    { w: "PIANO", h: "instrument" },
    { w: "OCEAN", h: "lots of water" },
    { w: "ROBOT", h: "a machine" },
    { w: "GHOST", h: "spooky" },
    // Not just "a fruit": that hint fits MELON just as well, and MELON is a
    // letter-for-letter anagram of LEMON.
    { w: "LEMON", h: "a sour yellow fruit" },
    { w: "STORM", h: "weather" },
    { w: "CROWN", h: "royalty wears it" },
    { w: "PIXEL", h: "a tiny screen dot" },
    { w: "NINJA", h: "a stealthy fighter" },
    { w: "COMET", h: "in space" },
    { w: "MAPLE", h: "a tree" },
    { w: "VENOM", h: "from a snake" },
    { w: "LASER", h: "a beam of light" },
    { w: "ZEBRA", h: "animal" },
    { w: "KOALA", h: "animal" },
    { w: "OTTER", h: "animal" },
    { w: "MOOSE", h: "animal" },
    { w: "SHARK", h: "a sea animal" },
    { w: "WHALE", h: "a sea animal" },
    { w: "SNAIL", h: "a slow crawler" },
    { w: "EAGLE", h: "a bird" },
    { w: "RAVEN", h: "a black bird" },
    { w: "STORK", h: "a long-legged bird" },
    { w: "CAMEL", h: "animal" },
    { w: "HORSE", h: "animal" },
    { w: "RHINO", h: "a big horned animal" },
    { w: "BISON", h: "animal" },
    { w: "SLOTH", h: "a very slow animal" },
    { w: "GECKO", h: "a small lizard" },
    { w: "VIPER", h: "a snake" },
    { w: "CORAL", h: "it grows in the sea" },
    { w: "BEACH", h: "sand by the sea" },
    { w: "RIVER", h: "water that flows" },
    { w: "CLOUD", h: "in the sky" },
    { w: "FROST", h: "weather" },
    { w: "STEAM", h: "hot water vapour" },
    { w: "MARSH", h: "wet muddy ground" },
    { w: "STONE", h: "a rock" },
    { w: "AMBER", h: "fossil tree resin" },
    { w: "TOPAZ", h: "a gem" },
    { w: "PEARL", h: "from an oyster" },
    { w: "BRASS", h: "a metal" },
    { w: "STEEL", h: "a strong metal" },
    { w: "CANDY", h: "a sweet treat" },
    { w: "BREAD", h: "food" },
    { w: "HONEY", h: "bees make it" },
    { w: "OLIVE", h: "a small green fruit" },
    { w: "MANGO", h: "a fruit" },
    { w: "PEACH", h: "a fruit" },
    { w: "GRAPE", h: "a fruit" },
    { w: "SALAD", h: "food" },
    { w: "PASTA", h: "food" },
    { w: "FLOUR", h: "for baking" },
    { w: "SWORD", h: "a knight's blade" },
    { w: "TORCH", h: "it lights the dark" },
    { w: "CABIN", h: "a small wooden house" },
    { w: "TOWER", h: "a tall building" },
    { w: "ARENA", h: "where fights happen" },
    { w: "MEDAL", h: "you win it" },
    { w: "HERON", h: "a wading bird" },
    { w: "SKUNK", h: "animal" },
    { w: "LLAMA", h: "animal" },
    { w: "ONION", h: "a vegetable" },
    { w: "BASIL", h: "a herb" },
    { w: "THYME", h: "a herb" },
    { w: "COCOA", h: "a chocolate powder" },
    { w: "FLUTE", h: "a woodwind instrument" },
    { w: "CELLO", h: "a large string instrument" },
    { w: "BANJO", h: "a plucked instrument" },
    { w: "ORBIT", h: "a path in space" },
    { w: "LUNAR", h: "of the moon" },
    { w: "CREEK", h: "a small stream" },
    { w: "CLIFF", h: "a steep drop" },
    { w: "SCARF", h: "neckwear" },
    { w: "GLOVE", h: "handwear" },
    { w: "DRESS", h: "clothing" },
    { w: "CHESS", h: "a board game" },
  ],
  6: [
    { w: "PLANET", h: "in space" },
    { w: "DRAGON", h: "a mythical beast" },
    { w: "GUITAR", h: "instrument" },
    { w: "JUNGLE", h: "a dense forest" },
    { w: "ROCKET", h: "it flies to space" },
    { w: "CASTLE", h: "royalty lives here" },
    { w: "WIZARD", h: "casts spells" },
    { w: "FALCON", h: "a bird" },
    { w: "SILVER", h: "a metal" },
    { w: "PYTHON", h: "a snake" },
    { w: "GARLIC", h: "in the kitchen" },
    { w: "MARBLE", h: "a stone or a toy" },
    { w: "TEMPLE", h: "a place of worship" },
    { w: "ZOMBIE", h: "the undead" },
    { w: "BADGER", h: "animal" },
    { w: "BEAVER", h: "animal" },
    { w: "COYOTE", h: "animal" },
    { w: "DONKEY", h: "animal" },
    { w: "GERBIL", h: "a small pet" },
    { w: "IGUANA", h: "a large lizard" },
    { w: "JAGUAR", h: "a wild cat" },
    { w: "LIZARD", h: "animal" },
    { w: "MONKEY", h: "animal" },
    { w: "OYSTER", h: "a sea animal" },
    { w: "PARROT", h: "a colourful bird" },
    { w: "PUFFIN", h: "a seabird" },
    { w: "RABBIT", h: "animal" },
    { w: "SALMON", h: "a fish" },
    { w: "TURTLE", h: "a sea animal" },
    { w: "WALRUS", h: "a sea animal" },
    { w: "WEASEL", h: "animal" },
    { w: "MANTIS", h: "a praying insect" },
    // Not THRONE, which is a letter-for-letter anagram of this.
    { w: "HORNET", h: "a stinging insect" },
    { w: "SPIDER", h: "it spins a web" },
    { w: "CANYON", h: "a deep valley" },
    { w: "DESERT", h: "dry and sandy" },
    { w: "GEYSER", h: "hot water shoots up" },
    { w: "ISLAND", h: "land in the sea" },
    { w: "LAGOON", h: "calm shallow water" },
    { w: "METEOR", h: "it streaks across the sky" },
    { w: "GALAXY", h: "millions of stars" },
    { w: "SATURN", h: "a planet" },
    { w: "NEBULA", h: "a cloud of space dust" },
    { w: "SUNSET", h: "the day ends" },
    { w: "SHOWER", h: "rain for a short while" },
    { w: "COPPER", h: "a metal" },
    { w: "NICKEL", h: "a metal" },
    { w: "QUARTZ", h: "a mineral" },
    { w: "BRONZE", h: "a metal" },
    { w: "FOSSIL", h: "ancient remains in rock" },
    { w: "ANCHOR", h: "it holds a ship" },
    { w: "CANDLE", h: "it burns and glows" },
    { w: "HAMMER", h: "a tool" },
    { w: "LADDER", h: "you climb it" },
    { w: "BUCKET", h: "you carry water in it" },
    { w: "PENCIL", h: "you write with it" },
    { w: "SHOVEL", h: "you dig with it" },
    { w: "HELMET", h: "it protects your head" },
    { w: "MARKET", h: "you shop here" },
    { w: "MAGNET", h: "it attracts iron" },
    { w: "TOUCAN", h: "a tropical bird" },
    { w: "SHRIMP", h: "sea creature" },
    { w: "BANANA", h: "a yellow fruit" },
    { w: "ORANGE", h: "a citrus fruit" },
    { w: "CHERRY", h: "a small red fruit" },
    { w: "PAPAYA", h: "a tropical fruit" },
    { w: "CARROT", h: "an orange vegetable" },
    { w: "POTATO", h: "a starchy vegetable" },
    { w: "PEPPER", h: "a spice" },
    { w: "WALNUT", h: "a nut" },
    { w: "CASHEW", h: "a nut" },
    { w: "GRAVEL", h: "small stones" },
    { w: "VIOLIN", h: "a bowed instrument" },
    { w: "TUNDRA", h: "cold landform" },
    { w: "WINTER", h: "a season" },
    { w: "SPRING", h: "a season" },
    { w: "SUMMER", h: "a season" },
    { w: "AUGUST", h: "a month" },
    { w: "JACKET", h: "clothing" },
    { w: "MITTEN", h: "handwear" },
    { w: "SANDAL", h: "footwear" },
    { w: "ERASER", h: "for correcting" },
    { w: "WRENCH", h: "a tool" },
  ],
  7: [
    { w: "DIAMOND", h: "a gem" },
    { w: "GRAVITY", h: "it pulls you down" },
    { w: "PENGUIN", h: "animal" },
    { w: "VOLCANO", h: "it erupts" },
    { w: "CAPTAIN", h: "leads a ship" },
    { w: "MONSTER", h: "a scary creature" },
    { w: "CRYSTAL", h: "a shiny mineral" },
    { w: "THUNDER", h: "weather" },
    { w: "JOURNEY", h: "a long trip" },
    { w: "MYSTERY", h: "a puzzle to solve" },
    { w: "OCTOPUS", h: "a sea animal" },
    { w: "DOLPHIN", h: "a sea animal" },
    { w: "LEOPARD", h: "animal" },
    { w: "TORNADO", h: "weather" },
    { w: "CHEETAH", h: "the fastest land animal" },
    { w: "GIRAFFE", h: "the tallest animal" },
    { w: "GORILLA", h: "an ape" },
    { w: "HAMSTER", h: "a small pet" },
    { w: "MEERKAT", h: "animal" },
    { w: "PANTHER", h: "a big black cat" },
    { w: "BUFFALO", h: "animal" },
    { w: "MUSTANG", h: "a wild horse" },
    { w: "REPTILE", h: "a scaly cold-blooded animal" },
    { w: "PELICAN", h: "a bird" },
    { w: "OSTRICH", h: "a huge bird" },
    { w: "PEACOCK", h: "a bird with a fancy tail" },
    { w: "GLACIER", h: "a river of ice" },
    { w: "GRANITE", h: "a hard rock" },
    { w: "MINERAL", h: "dug from the ground" },
    { w: "EMERALD", h: "a green gem" },
    { w: "ECLIPSE", h: "the sun goes dark" },
    { w: "COMPASS", h: "it points north" },
    { w: "LANTERN", h: "it lights the dark" },
    { w: "CIRCUIT", h: "electricity flows round it" },
    { w: "BATTERY", h: "it stores power" },
    { w: "MONITOR", h: "you look at it" },
    { w: "NETWORK", h: "computers linked up" },
    { w: "PROGRAM", h: "code a computer runs" },
    { w: "CONSOLE", h: "you play games on it" },
    { w: "MACHINE", h: "it does the work" },
    { w: "FACTORY", h: "where things are made" },
    { w: "FURNACE", h: "a very hot oven" },
    { w: "GEARBOX", h: "it changes the gears" },
    { w: "TRAILER", h: "it gets towed" },
    { w: "BICYCLE", h: "you pedal it" },
    { w: "AIRSHIP", h: "it floats in the sky" },
    { w: "HARBOUR", h: "boats rest here" },
    { w: "PYRAMID", h: "an ancient tomb" },
    { w: "VILLAGE", h: "a small town" },
    { w: "COTTAGE", h: "a small country house" },
    { w: "CHIMNEY", h: "smoke goes up it" },
    { w: "BALCONY", h: "you stand out on it" },
    { w: "KITCHEN", h: "you cook here" },
    { w: "LIBRARY", h: "full of books" },
    { w: "STADIUM", h: "where crowds watch sport" },
    { w: "MUSICAL", h: "a play full of songs" },
    { w: "CONCERT", h: "live music" },
    { w: "TRUMPET", h: "instrument" },
    { w: "PHANTOM", h: "a ghost" },
    { w: "PUMPKIN", h: "you carve it" },
    { w: "AVOCADO", h: "a green fruit" },
    { w: "APRICOT", h: "a stone fruit" },
    { w: "CABBAGE", h: "a leafy vegetable" },
    { w: "SPINACH", h: "a leafy green" },
    { w: "LETTUCE", h: "a salad leaf" },
    { w: "PARSLEY", h: "a herb" },
    { w: "VANILLA", h: "a flavour" },
    { w: "CARAMEL", h: "a sweet sauce" },
    { w: "POPCORN", h: "a snack" },
    { w: "PRETZEL", h: "a knotted snack" },
    { w: "PRAIRIE", h: "grassland" },
    { w: "OCTOBER", h: "a month" },
    { w: "JANUARY", h: "a month" },
    { w: "BLANKET", h: "on a bed" },
    { w: "CUSHION", h: "a soft seat" },
    { w: "CABINET", h: "furniture" },
    { w: "CURTAIN", h: "it covers a window" },
  ],
  8: [
    { w: "DINOSAUR", h: "an extinct beast" },
    { w: "ELEPHANT", h: "animal" },
    { w: "MOUNTAIN", h: "you climb it" },
    { w: "SANDWICH", h: "food" },
    { w: "COMPUTER", h: "a machine" },
    { w: "AIRPLANE", h: "it flies" },
    { w: "HOSPITAL", h: "you go when sick" },
    { w: "UMBRELLA", h: "for the rain" },
    { w: "TREASURE", h: "pirates seek it" },
    { w: "NOTEBOOK", h: "you write in it" },
    { w: "STARFISH", h: "a sea animal" },
    { w: "PASSWORD", h: "keep it secret" },
    { w: "KANGAROO", h: "animal" },
    { w: "PANCAKES", h: "food" },
    { w: "SQUIRREL", h: "animal" },
    { w: "PHEASANT", h: "a game bird" },
    { w: "STINGRAY", h: "a flat sea fish" },
    { w: "ANTELOPE", h: "animal" },
    { w: "CHIPMUNK", h: "a small animal" },
    { w: "FLAMINGO", h: "a pink bird" },
    { w: "TORTOISE", h: "a slow animal" },
    { w: "SCORPION", h: "it has a stinging tail" },
    { w: "SEAHORSE", h: "a sea animal" },
    { w: "BARNACLE", h: "it sticks to ships" },
    { w: "MACKEREL", h: "a fish" },
    { w: "RAINFALL", h: "weather" },
    { w: "SNOWFALL", h: "weather" },
    { w: "BLIZZARD", h: "a fierce snowstorm" },
    { w: "MOONBEAM", h: "light from the moon" },
    { w: "SUNLIGHT", h: "light from the sun" },
    { w: "DAYBREAK", h: "the day begins" },
    { w: "ASTEROID", h: "a space rock" },
    { w: "STOCKADE", h: "a wooden fort" },
    { w: "CATAPULT", h: "it hurls rocks" },
    { w: "CROSSBOW", h: "it shoots bolts" },
    { w: "GAUNTLET", h: "an armoured glove" },
    { w: "NECKLACE", h: "you wear it" },
    { w: "BRACELET", h: "for your wrist" },
    { w: "SAPPHIRE", h: "a blue gem" },
    { w: "PLATINUM", h: "a precious metal" },
    { w: "TELEGRAM", h: "an old-fashioned message" },
    { w: "HEADLINE", h: "the top of a news story" },
    { w: "MAGAZINE", h: "you read it" },
    { w: "DOCUMENT", h: "an official paper" },
    { w: "POSTCARD", h: "you send it on holiday" },
    { w: "KEYBOARD", h: "you type on it" },
    { w: "JOYSTICK", h: "you play games with it" },
    { w: "SOFTWARE", h: "programs on a computer" },
    { w: "HARDWARE", h: "the physical parts" },
    { w: "TERMINAL", h: "a computer screen" },
    { w: "FIREWALL", h: "it blocks intruders" },
    { w: "ELEVATOR", h: "it takes you up" },
    { w: "STAIRWAY", h: "it goes up a floor" },
    { w: "BASEMENT", h: "the floor below" },
    { w: "ARMCHAIR", h: "you sit in it" },
    { w: "CUPBOARD", h: "you store plates in it" },
    { w: "WARDROBE", h: "you hang clothes in it" },
    { w: "CURTAINS", h: "they cover a window" },
    { w: "PAINTING", h: "a picture in a frame" },
    { w: "CLARINET", h: "instrument" },
    { w: "REINDEER", h: "animal" },
    { w: "HEDGEHOG", h: "a spiny animal" },
    { w: "ZUCCHINI", h: "a green squash" },
    { w: "BROCCOLI", h: "a green vegetable" },
    { w: "CUCUMBER", h: "a salad vegetable" },
    { w: "EGGPLANT", h: "a purple vegetable" },
    { w: "MUSHROOM", h: "a fungus" },
    { w: "OBSIDIAN", h: "volcanic glass" },
    { w: "HIGHLAND", h: "a landform" },
    { w: "NOVEMBER", h: "a month" },
    { w: "DECEMBER", h: "a month" },
    { w: "FEBRUARY", h: "a month" },
    { w: "BACKPACK", h: "for carrying" },
    { w: "SUITCASE", h: "for travel" },
    { w: "SAILBOAT", h: "it uses wind" },
    { w: "LADYBIRD", h: "a spotted beetle" },
    { w: "DUMPLING", h: "a small dough parcel" },
  ],
};
