/**
 * Word pools for Panic Type. Daily prompts are drawn from these with the
 * seeded RNG, escalating short word → word pair → full phrase.
 */

export const SHORT_WORDS = [
  "zap", "run", "go", "hex", "jam", "fizz", "bolt", "dash", "grip", "jolt",
  "keys", "lava", "mint", "nova", "onyx", "pixel", "quick", "rush", "snap",
  "tilt", "vex", "wave", "yell", "zip", "buzz", "clap", "dive", "echo",
  "flux", "glow", "hype", "iris", "jinx", "kick", "loop", "mode", "neon",
  "opal", "pace", "quiz", "risk", "spin", "trap", "urge", "volt", "warp",
] as const;

export const MEDIUM_WORDS = [
  "arcade", "blister", "cascade", "dazzle", "eclipse", "frantic", "gizmo",
  "haywire", "impulse", "jackpot", "kinetic", "livewire", "mayhem", "nimble",
  "orbital", "panicky", "quicken", "reactor", "scramble", "tornado",
  "unravel", "vibrant", "whiplash", "xylophone", "yardstick", "zealous",
  "adrenaline", "backfire", "circuitry", "detonate", "electric", "flashback",
  "gauntlet", "hyperdrive", "ignition", "juggernaut", "overclock", "pressure",
  "quicksand", "rampage", "shockwave", "turbulent", "ultimatum", "voltage",
] as const;

/** The arcade's own voice — self-aware jabs at the player and the clock. */
const ARCADE_PHRASES = [
  "Keep your cool.",
  "Type or be typed.",
  "No pressure at all!",
  "The clock is lying.",
  "Faster, but neater.",
  "Don't look down now.",
  "Blink and you lose.",
  "Steady hands, hot keys.",
  "Panic is a choice; refuse it.",
  "Your keyboard is on fire!",
  "Speed thrills, typos kill.",
  "One more prompt, they said.",
  "Breathe in, hammer keys, breathe out.",
  "The semicolon is watching you; behave.",
  "Caps, commas, chaos - in that order.",
  "Who put punctuation in a speed test?!",
  "Somewhere, a timer laughs at you.",
  "Accuracy first, glory second, panic third.",
  "You've trained your whole life for this.",
  "Warning: this phrase contains a comma, obviously.",
  "Quick! The quota won't fill itself.",
  "Hold the line - every letter counts!",
  "Fingers, don't fail me now.",
  "It's not a typo; it's improvisation.",
  "Ninety percent panic, ten percent typing.",
  "Read twice, type once, cry later.",
  "The backspace key files a complaint.",
  "May your fingers be ever nimble.",
  "This sentence self-destructs in seconds.",
  "Overload achieved; brain rebooting now...",
] as const;

/**
 * Pop-culture lines — the fun half of the pool. Recognizing one mid-panic is
 * half the joy, so these lean famous over obscure.
 *
 * Rules for anything added here:
 *  - Keep it under ~50 characters. Late prompts allow 0.26s/char, so a longer
 *    line turns into an endurance test rather than a burst of speed.
 *  - Straight apostrophes only, and no em dashes or curly quotes. `typeable()`
 *    in TypingGame rewrites them anyway, but then the prompt on screen no
 *    longer matches what was written here.
 *  - Short quoted lines only. Never paste a full verse of song lyrics.
 */
export const POP_PHRASES = [
  // Sci-fi & space opera
  "May the Force be with you.",
  "I have a bad feeling about this.",
  "Do. Or do not. There is no try.",
  "It's a trap!",
  "These aren't the droids you're looking for.",
  "Never tell me the odds!",
  "Help me, Obi-Wan Kenobi.",
  "This is the way.",
  "Punch it, Chewie.",
  "Let the Wookiee win.",
  "I love you. I know.",
  "Now this is podracing!",
  "Live long and prosper.",
  "Resistance is futile.",
  "Make it so.",
  "Beam me up, Scotty.",
  "Open the pod bay doors, HAL.",
  "I'm sorry, Dave. I can't do that.",
  "In space, no one can hear you.",
  "Game over, man! Game over!",
  "Stay frosty.",
  "Nuke it from orbit.",
  "Klaatu barada nikto.",
  "Exterminate!",
  "Allons-y!",
  "The truth is out there.",

  // Action & thrillers
  "Hasta la vista, baby.",
  "I'll be back.",
  "Come with me if you want to live.",
  "I want to play a game.",
  "Yippee-ki-yay!",
  "Welcome to the party, pal!",
  "Say hello to my little friend!",
  "You talking to me?",
  "Go ahead, make my day.",
  "Do you feel lucky, punk?",
  "Bond. James Bond.",
  "Shaken, not stirred.",
  "I feel the need for speed.",
  "Talk to me, Goose.",
  "Houston, we have a problem.",
  "Failure is not an option.",
  "This is Sparta!",
  "Are you not entertained?",
  "Freedom!",
  "My name is Inigo Montoya.",
  "As you wish.",
  "Inconceivable!",
  "Have fun storming the castle!",
  "You're gonna need a bigger boat.",
  "Wax on, wax off.",

  // Crime & drama
  "Say my name.",
  "I am the one who knocks.",
  "Yeah, science!",
  "Better call Saul.",
  "Leave the gun. Take the cannoli.",
  "Keep your friends close.",
  "Say what again!",
  "Zed's dead, baby.",
  "That's a tasty burger!",
  "Round up the usual suspects.",
  "Here's looking at you, kid.",
  "Of all the gin joints...",
  "The Dude abides.",
  "Shut up, Donny.",
  "That rug really tied the room together.",
  "You are not your job.",
  "I see dead people.",
  "Here's Johnny!",
  "You can't handle the truth!",
  "Show me the money!",

  // Fantasy & adventure
  "You shall not pass!",
  "One does not simply walk in.",
  "My precious.",
  "A wizard is never late.",
  "Fly, you fools!",
  "I am no man.",
  "You're a wizard, Harry.",
  "Expecto Patronum!",
  "Mischief managed.",
  "After all this time? Always.",
  "Winter is coming.",
  "You know nothing, Jon Snow.",
  "Valar morghulis.",
  "A Lannister always pays his debts.",
  "The North remembers.",
  "I drink and I know things.",
  "Chaos is a ladder.",
  "The night is dark and full of terrors.",
  "Life finds a way.",
  "Hold on to your butts.",
  "Clever girl.",
  "Welcome to Jurassic Park.",
  "There's no place like home.",
  "Great Scott!",
  "Roads? Where we're going we don't need roads.",

  // The Matrix
  "There is no spoon.",
  "Follow the white rabbit.",
  "I know kung fu.",
  "Wake up, Neo.",
  "Red pill or blue pill?",
  "Dodge this.",

  // Superheroes
  "I am Iron Man.",
  "I can do this all day.",
  "Avengers, assemble!",
  "I am Groot.",
  "With great power comes great responsibility.",
  "Wakanda forever!",
  "I love you three thousand.",
  "That's my secret: I'm always angry.",
  "Why so serious?",
  "I'm Batman.",
  "Some men just want to watch it burn.",

  // Animation & family
  "To infinity and beyond!",
  "Just keep swimming.",
  "Hakuna Matata.",
  "Adventure is out there!",
  "You're my favorite deputy.",
  "That'll do, pig.",
  "Squirrel!",
  "Big mistake. Huge.",
  "D'oh!",
  "Eat my shorts.",
  "Cowabunga, dude!",

  // Video games
  "It's-a me, Mario!",
  "The cake is a lie.",
  "Would you kindly?",
  "A man chooses; a slave obeys.",
  "Finish him!",
  "Hey! Listen!",
  "War. War never changes.",
  "Do a barrel roll!",
  "Praise the sun!",
  "You died.",
  "Objection!",
  "Snake? Snake! Snaaake!",
  "I used to be an adventurer like you.",
  "Stay a while and listen.",
  "Nothing is true; everything is permitted.",
  "Requiescat in pace.",
  "Wake up, Mr. Freeman.",
  "Rise and shine.",
  "Gotta go fast!",
  "Leeeeeroy Jenkins!",
  "Press F to pay respects.",
  "It's dangerous to go alone.",
  "Thank you, but our princess is elsewhere.",
  "Get over here!",
  "Hadouken!",
  "The right man in the wrong place.",

  // Anime
  "It's over nine thousand!",
  "Kamehameha!",
  "Believe it!",
  "Plus Ultra!",
  "Yare yare daze.",
  "Ora ora ora!",
  "Za Warudo!",
  "Nani?!",
  "I'm gonna be King of the Pirates!",
  "Stand proud; you're strong.",
  "Omae wa mou shindeiru.",
  "I'll take a potato chip and eat it!",
  "Total concentration breathing!",

  // Sitcoms & TV
  "Bazinga!",
  "How you doin'?",
  "We were on a break!",
  "That's what she said.",
  "Bears. Beets. Battlestar Galactica.",
  "I declare bankruptcy!",
  "Legendary!",
  "Suit up!",
  "Yada, yada, yada.",
  "No soup for you!",
  "Stay classy.",
  "I love lamp.",
  "Milk was a bad choice.",
  "Sixty percent of the time it works.",
  "Nobody puts Baby in a corner.",
  "Life is like a box of chocolates.",
  "Run, Forrest, run!",
  "There is no crying in baseball!",
  "Be excellent to each other.",
  "Party on, dudes!",
  "We're not worthy!",
  "As if!",
  "On Wednesdays we wear pink.",
  "She doesn't even go here!",
  "That's so fetch!",
  "The limit does not exist.",
  "Talk to the hand.",
  "Keep the change, you filthy animal.",
  "Who you gonna call?",
  "Don't cross the streams.",
  "Elementary, my dear Watson.",
  "The game is afoot.",
  "It's alive! It's alive!",
  "E.T. phone home.",

  // Internet & tech
  "All your base are belong to us.",
  "Hello, world!",
  "This is fine.",
  "I'm in danger.",
  "Task failed successfully.",
  "It works on my machine.",
  "Have you tried turning it off?",
  "404: prompt not found.",
  "Deal with it.",
  "Ship it!",
] as const;

/** The full phrase pool Panic Type draws from. */
export const PHRASES: readonly string[] = [
  ...ARCADE_PHRASES,
  ...POP_PHRASES,
];
